# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DfdlfP63wjTsiaGU2SwEPBtsToRWmGZu
"""

import pandas as pd
import numpy as np

weather = pd.read_csv("weather_basel.csv")

weather = weather.iloc[9:]
weather = weather.rename(columns={"location": "date"})
weather = weather.rename(columns={"Basel": "temperature"})
weather.head(10)

weather['date'] = pd.to_datetime(weather['date'])

weather.head(20)

weather.drop(['Basel.1', 'Basel.2','Basel.3'], axis=1)

import plotly.express as px

weather['temperature'] = weather['temperature'].astype(float)

weather['temperature'] = weather['temperature'].round(decimals = 1)

chart1 = px.line(data_frame=weather,
           x="date",
           y="temperature",

          #  size=[1.0]*8784,
           title="average temperature")
chart1

import dash
import dash_core_components as dcc
import dash_html_components as html

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

graph1 = dcc.Graph(
        id='graph1',
        figure=chart1,
        style={'width': '180vh'},
        className="six columns"
    )

header = html.H2(children="Dashboard by Kuzma Fedorovich")

row2 = html.Div(children="This dashboard represents median air temperature in Basel, Switzerland, year 2021")

row1 = html.Div(children=[graph1],)

layout = html.Div(children=[header, row2, row1], style={"text-align": "center"})

app.layout = layout

if __name__ == "__main__":
    app.run_server(debug=True)
